###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################
defaults:
  -
    scope:
      path: "**/*.md"
    values:
      layout: "default"
# Name of website
title: Shuebox Educational Services

# Your name to show in the footer
author: Rebecca Shue
skin: night
###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  IEW Classes: "iew-classes"
  Literacy Assessments and Tutoring: "tutoring"

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "rebecca.m.shue@outlook.com"